### ISSUE TITLE
Can't remove a vote if all votes are added

### ISSUE THREAD

**Issue by NogginBops** [SpaceKrakens/Ranked-Vote#14]
@powli said that this is because the container for the voting options is removed if it's empty.

Is there a way to also make that area/container more visible as it's kind of hard to see where you should drag back an option? Like setting a minimum size?

**Comment by powli** [comment]
To clarify: it's technically not removed, but it's height get's reduced to 0, so it is impossible to move options back into it.

I would propose adding a min-height and a light grey background to the available option box, so it's easier to see and put stuff into it.

**Comment by powli** [comment]
@longtomjr  fix it! 😆
