### ISSUE TITLE
On poll creation show the owner and the name of your repositories.

### ISSUE THREAD

**Issue by longtomjr** [SpaceKrakens/Ranked-Vote#20]
Currently it only shows the name. This results in a bit of a problem because I have 3 ranked-vote repositories I have access to. There is a couple of ways we can try to do this.
* `Owner - Name`
* `Owner/Name` - might need to get the link for this.

**Comment by powli** [comment]
I guess it would be better to actually store the owner of the repo/project too. Therefore we need to:
- adjust the model
- adjust the importer
- finally adjust the template to display owner/name

**Comment by powli** [comment]
@longtomjr I added the utility function as mentioned in Discord today and changed the templates to use it

**Comment by longtomjr** [comment]
Ty, Closing this.
